platform:
  "Общие сервисы":
    services:
      - 1481 RCS Распознавание документов
      - 1497 DOSE Досье ЮЛ/ФЛ
      - 1498 CSOC Карточка ЮЛ
      - 1511 CSRF Кросс-ссылки ЮЛ
      - 1512 CSEP Расширенный профиль ЮЛ
      - 1536 CPPS ОПС Продуктовый профиль
      - 1550 CSES Данные ЮЛ из внешних источников
      - 1570 UPZO Операционные задачи
      - 1577 CCS Комплаенс
      - 1578 FXRT Курсы валют
      - 1583 LECS Лиды ЮЛ
      - 1584 MOLE Маркетинговые предложения ЮЛ
      - 1630 OACS Полномочия представителя ЮЛ
      - 1717 CACS Активности с корпоративным клиентом
      - USBS
      - 1750 УПИО
    users:
      - Левин Дмитрий
      - Осипенко Василий
      - Воронцов Евгений
      - Ильин Павел
      - Шищенко Павел
      - Степанов Иван
      - Брагин Максим
      - Носачев Алексей
      - Малинко Александр
      - Ткачев Геннадий
      - Яковлев Сергей
      - Ларионова Александра
      - Ольшанников Илья
      - Илья Чуляев
      - Артур Шагиахметов
      - Никита Ильин
  "Служебные сервисы":
    services:
      - 1389 TSAU Аудит
      - 1403 TSEC Сервис хранения контента СХК/ЕСМ
      - 1404 TSLG Журналирование
      - 1406 TSAM Прикладной и системный мониторинг
      - 1407 TSSH Планировщик заданий
      - 1408 TSCT Сессионные данные
      - 1409 TSAC Консоль управления
      - 1410 TSKC Управление ключами и сертификатами
      - 1412 TSTR Трассировка
      - 1413 TSES Электронная подпись
      - 1425 TSAJ Прикладной журнал
      - 1440 TSRM Ролевая модель
      - 1586 OSRF Реестр Справочников
      - 1588 TSID  Генератор идентификаторов
      - 1609 TSSS Cтриминг в платформу данных
      - 1725 OSES Единый интерфейс электронной подписи
    users:
      - Сотрудники не заданы
  "ЕПА":
    services:
    - 1473 EPAA Единая платформа аутентификации
    - 1474 TYK Платформа внутренних API
    - 1448 APIC Платформа внешних API
    - 1493 SWH Реестр API
    - 1547 HINT Конструктор подсказок
    - 1666 FSRV Файловый обмен с партнерами
    users:
    - Сотрудники не заданы
  "УИП":
    services:
    - 1369_3 Messaging Шина
    - 1369_2 MSA Микросервис
    - 1369_1 ServiceMesh Сервис меш
    - Аrtemis
    - СФП
    users:
    - Сотрудники не заданы
